import http from './http'

export const getMusicResourcesApi = (params) => http.get('/api/music/v1/music-resources', { params })
export const getMyMusicResourcesApi = () => http.get('/api/music/v1/me/music-resources')
export const getMusicResourcesByIdsApi = (ids) => http.get('/api/music/v1/music-resources/by-ids', { params: { ids } })
export const getMusicResourceDetailApi = (musicId) => http.get(`/api/music/v1/music-resources/${musicId}`)
export const getMusicResourceTagsApi = (musicId) => http.get(`/api/music/v1/music-resources/${musicId}/tags`)
export const createMusicResourceApi = (payload) => http.post('/api/music/v1/music-resources', payload)
export const updateMusicResourceApi = (musicId, payload) => http.put(`/api/music/v1/music-resources/${musicId}`, payload)
export const deleteMusicResourceApi = (musicId) => http.delete(`/api/music/v1/music-resources/${musicId}`)
export const replaceMusicTagsApi = (musicId, payload) => http.post(`/api/music/v1/music-resources/${musicId}/tags`, payload)
export const getOfficialPlaylistConfigsApi = () => http.get('/api/music/v1/official-playlists')
export const updateOfficialPlaylistConfigApi = (playlistKey, payload) => http.put(`/api/music/v1/official-playlists/${encodeURIComponent(playlistKey)}`, payload)
export const getEmotionTagsApi = () => http.get('/api/music/v1/emotion-tags')
export const getEmotionTagByNameApi = (name) => http.get('/api/music/v1/emotion-tags/by-name', { params: { name } })
export const createEmotionTagApi = (payload) => http.post('/api/music/v1/emotion-tags', payload)

export const getMyMusicPreferencesApi = () => http.get('/api/music/v1/me/music-preferences')
export const upsertMusicPreferenceApi = (payload) => http.post('/api/music/v1/me/music-preferences', payload)
export const deleteMusicPreferenceApi = (musicId, preferenceType) => http.delete(`/api/music/v1/me/music-preferences/${musicId}/${preferenceType}`)
export const getMusicPreferenceByMusicApi = (musicId) => http.get(`/api/music/v1/me/music-preferences/by-music/${musicId}`)
export const recommendMusicByEmotionApi = (payload) => http.post('/api/music/v1/me/music-recommendations/by-emotion', payload)
export const recommendNextMusicApi = (payload) => http.post('/api/music/v1/me/music-recommendations/next', payload)

export const getMyPlaylistsApi = () => http.get('/api/music/v1/me/playlists')
export const getMyPlaylistApi = (id) => http.get(`/api/music/v1/me/playlists/${id}`)
export const createPlaylistApi = (payload) => http.post('/api/music/v1/me/playlists', payload)
export const updatePlaylistApi = (id, payload) => http.put(`/api/music/v1/me/playlists/${id}`, payload)
export const deletePlaylistApi = (id) => http.delete(`/api/music/v1/me/playlists/${id}`)

export const addTrackToPlaylistApi = (id, payload) => http.post(`/api/music/v1/me/playlists/${id}/tracks`, payload)
export const removeTrackFromPlaylistApi = (id, musicId) => http.delete(`/api/music/v1/me/playlists/${id}/tracks/${encodeURIComponent(musicId)}`)
